module.exports={
    test:{
        client:'pg',
        version:'9.6',
        connection:{
            host:'localhost',
            user:'postgres',
            password:'admin',
            database:'db_test'
        },
        migrations:{
            directory:'src/migrations'
        }
    }
}